server:
  port: 9097
  
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
   
      discovery:
        locator:
          enabled: true
      routes:
      - id: new-sale-service
        uri: http://localhost:8081
        predicates:
        - Path=/new-sale/**
        filters:
        - RewritePath=/new-sale/(?<path>.*), /$\{path}
        - AuthFilter
      
      - id: customer-management-service
        uri: http://localhost:8082
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: hsn-details-service
        uri: http://localhost:8083
        predicates:
        - Path=/hsn-details/**
        filters:
        - RewritePath=/hsn-details/(?<path>.*), /$\{path}
        - AuthFilter
      
      - id: user-management-service
        uri: http://usermanagement:8084
        predicates:
        - Path=/user-management/**
        filters:
        - RewritePath=/user-management/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: userStore-mappaing-service
        uri: http://localhost:8085/
        predicates:
        - Path=/user-store/**
        filters:
        - RewritePath=/user-store/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: paymentgateway-service
        uri: http://localhost:8086/
        predicates:
        - Path=/paymentgateway/**
        filters:
        - RewritePath=/paymentgateway/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: promo-exchange-service
        uri: http://localhost:8087/
        predicates:
        - Path=/promo-exchange/**
        filters:
        - RewritePath=/promo-exchange/(?<path>.*), /$\{path}
        - AuthFilter
        
        
      - id: tax-master-service
        uri: lb://tax-master-service
        predicates:
        - Path=/tax-master/**
        filters:
        - RewritePath=/tax-master/(?<path>.*), /$\{path}
        - AuthFilter
        
       
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
                        
        
eureka:
  serviceUrl:
      defaultZone:http//service-registry:8762/eureka/

app:
 setWebEnvironment(false);


#####################properties related for aws cognito for authentication provider####################

Cognito:
     aws: 
        accesskey: AKIAYZOXA3O4HNGVWCQL
        secret_access_key: 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 
        client_id: 2640gqqchl9bhtoaipi09de0nr
        userpool_id: ap-south-1_W7vTQcho9
        region: ap-south-1
        idTokenPoolUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_W7vTQcho9
logging:
   level:
      org:
       springframework:
                security:
                       web:
                         FilterChainProxy : debug
    
###################################### End #################################################