server:
  port: 9097
  
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
   
      discovery:
        locator:
          enabled: true
      routes:
      - id: new-sale-api 
        uri: http://10.100.161.5:8081
        predicates:
        - Path=/new-sale/**
        filters:
        - RewritePath=/new-sale/(?<path>.*), /$\{path}
        - AuthFilter
      
      - id: customer-management
        uri: http://10.100.67.139:8082
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: hsn-details 
        uri: http://10.100.177.121:8083
        predicates:
        - Path=/hsn-details/**
        filters:
        - RewritePath=/hsn-details/(?<path>.*), /$\{path}
        - AuthFilter
      
      - id: usermanagement 
        uri: http://10.100.160.240:8084
        predicates:
        - Path=/user-management/**
        filters:
        - RewritePath=/user-management/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: user-store-mapping 
        uri: http://10.100.74.36:8081/
        predicates:
        - Path=/user-store/**
        filters:
        - RewritePath=/user-store/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: payment-gateway
        uri: http://10.100.143.95:8086/
        predicates:
        - Path=/paymentgateway/**
        filters:
        - RewritePath=/paymentgateway/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: promo-exchange
        uri: http://10.100.82.250:8088/
        predicates:
        - Path=/promo-exchange/**
        filters:
        - RewritePath=/promo-exchange/(?<path>.*), /$\{path}
        - AuthFilter
        
        
      - id: tax-master
        uri: http://10.100.178.125:8088/
        predicates:
        - Path=/tax-master/**
        filters:
        - RewritePath=/tax-master/(?<path>.*), /$\{path}
        - AuthFilter
        
        
      - id: catalog-service
        uri: http://10.100.195.69:8085/
        predicates:
        - Path=/catalog-categories/**
        filters:
        - RewritePath=/catalog-categories/(?<path>.*), /$\{path}
         - AuthFilter
        
      - id: inventory-module
        uri: http://10.100.15.219:9092/
        predicates:
        - Path=/inventory/**
        filters:
        - RewritePath=/inventory/(?<path>.*), /$\{path}
         - AuthFilter
     
     
      - id: connection-pool
        uri: http://10.100.181.193:8085/
        predicates:
        - Path=/connection-pool/**
        filters:
        - RewritePath=/connection-pool/(?<path>.*), /$\{path}
      - AuthFilter
        
       
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        
      
          
        
eureka:
  serviceUrl:
      defaultZone:http//10.100.143.45:8762:8762/eureka/

app:
 setWebEnvironment(false);


#####################properties related for aws cognito for authentication provider####################

Cognito:
     aws: 
        accesskey: AKIAYZOXA3O4HNGVWCQL
        secret_access_key: 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 
        client_id: 1tk6nn66mll5thvmgdlnuo54fi
        userpool_id: ap-south-1_gttd6A4tT
        region: ap-south-1
        idTokenPoolUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_gttd6A4tT
logging:
   level:
      org:
       springframework:
                security:
                       web:
                         FilterChainProxy : debug
    
###################################### End #################################################
#