apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: default
spec:
  selector:
    matchLabels: 
      app: apigateway
  replicas: 1
  template:
    metadata:
      name: apigateway
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: 881289302514.dkr.ecr.ap-south-1.amazonaws.com/apigateway # repository 
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: LoadBalancer
  ports:
    - port: 9097
  selector:
    app: apigateway